### ISSUE TITLE
Writing a raycasting plugin

### ISSUE THREAD

**Issue by soulslicer** [team-vigir/vigir_ocs_common#1]
Good day,

I've been looking for rviz plugin examples that we can use to build our robot simulator, and we stumbled upon your stuff. We were trying to build lidar simulation directly as an rviz plugin that can work with markers etc, but say avoid the tf objects etc. However, we were having difficulty on how to proceed. Is there a package of yours we can reference?

**Comment by astumpf** [comment]
I can't follow your idea as RViz is not designed for simulation but only for visualization. However, to my knowledge we don't have any kind of such packages.
